name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.17.2
            otp: 26.2.5

    steps:
    - uses: actions/checkout@v1
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}
        disable_problem_matchers: true
        version-type: "strict"
    - name: Cache deps
      uses: actions/cache@v4
      with:
        path: |
          ~/.hex
          ~/.mix
          deps
        key: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-mix-
    - name: Cache build artifacts
      uses: actions/cache@v2
      with:
        path: |
          _build
          priv/plts
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    # https://elixirforum.com/t/github-action-cache-elixir-always-recompiles-dependencies-elixir-1-13-3/45994/12
    - name: Compile Deps
      run: mix loadpaths
    - name: Run Tests
      run: mix test
      if: always()
    - name: Credo
      run: MIX_ENV=test mix credo --strict
      if: always()
    - name: Formatting
      run: MIX_ENV=test mix format --check-formatted
      if: always()
    # - name: Dialyzer
    #   run: MIX_ENV=test mix dialyzer --halt-exit-status
    #   if: always()