name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.11.x
            otp: 23.2.x

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-elixir@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Cache build artifacts
      uses: actions/cache@v2
      with:
        path: |
          ~/.hex
          ~/.mix
          _build
          priv/plts
        key: ${{ matrix.otp }}-${{ matrix.elixir }}-static_analysis-build
    - name: Run Tests
      run: mix test
    - name: Run docception
      run: MIX_ENV=test mix docception README.md
    - name: Credo
      run: mix credo --strict
    - name: Dialyzer
      run: mix dialyzer --halt-exit-status
